package com.rd.robot.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

public class WorkflowNode {
    private String id; // unique node ID, generated by frontend

    @JsonProperty("agent_id")
    private long agentId;

    @JsonProperty("agent_name")
    private String agentName; // display redundancy

    @JsonProperty("input_template")
    private String inputTemplate; // template with {{var}} placeholders

    @JsonProperty("output_var")
    private String outputVar; // output variable name for downstream

    @JsonProperty("order_index")
    private int orderIndex; // 0-based execution order

    @JsonProperty("is_final")
    private boolean isFinal; // whether this is the final output node

    private String condition; // classification route condition, empty = unconditional

    @JsonProperty("next_nodes")
    private List<String> nextNodes; // DAG mode: downstream node IDs, empty = linear mode

    @JsonProperty("parallel_group")
    private String parallelGroup; // DAG mode: nodes in same group run in parallel

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public long getAgentId() { return agentId; }
    public void setAgentId(long agentId) { this.agentId = agentId; }
    public String getAgentName() { return agentName; }
    public void setAgentName(String agentName) { this.agentName = agentName; }
    public String getInputTemplate() { return inputTemplate; }
    public void setInputTemplate(String inputTemplate) { this.inputTemplate = inputTemplate; }
    public String getOutputVar() { return outputVar; }
    public void setOutputVar(String outputVar) { this.outputVar = outputVar; }
    public int getOrderIndex() { return orderIndex; }
    public void setOrderIndex(int orderIndex) { this.orderIndex = orderIndex; }
    public boolean isFinal() { return isFinal; }
    public void setFinal(boolean isFinal) { this.isFinal = isFinal; }
    public String getCondition() { return condition; }
    public void setCondition(String condition) { this.condition = condition; }
    public List<String> getNextNodes() { return nextNodes; }
    public void setNextNodes(List<String> nextNodes) { this.nextNodes = nextNodes; }
    public String getParallelGroup() { return parallelGroup; }
    public void setParallelGroup(String parallelGroup) { this.parallelGroup = parallelGroup; }
}